USE [MASTERDATA]
GO

/****** Objeto: View [dbo].[MATERIALES_FORMATO_SAP_TTM] Fecha de script: 31-08-2026 12:35:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





--SELECT * FROM CODIGOS_FABRICANTES

--select * from [dbo].[MATERIALES_FORMATO_SAP_TTM]

ALTER VIEW [dbo].[MATERIALES_FORMATO_SAP_TTM]
AS 
SELECT 

'MM01' AS TRANSACCION, 
'' AS MATERIAL,
'T' AS RAMO,
'ZVEH' AS TIPO_MATERIAL,
CENTRO AS CENTRO,
'' AS COL_01,
'' AS COL_02,
COD_FILIAL AS FILIAL,
CODIGO_CANAL AS CANAL, 
'X' AS COL_03,
'X' AS COL_04, 
'' AS COL_05,
'X' AS COL_06,
'' AS COL_07, 
'' AS COL_08,
'X' AS COL_09,
'X' AS COL_10,
'X' AS COL_11,
'X' AS COL_12,
'' AS COL_13,
'X' AS COL_14,
'X' AS COL_15,
'X' AS COL_16,
'X' AS COL_17,
'' AS COL_18,
'' AS COL_19,
'' AS COL_20,
'X' AS COL_21,
'' AS COL_22,
'' AS COL_23,
'' AS COL_24,
'' AS COL_25,
'' AS COL_26,
'UN' AS UNIDAD_MEDIDA,
TEXTO_BREVE AS TEXTO_BREVE, 
GRUPO_ARTICULOS AS GRUPO_ARTICULO,
COD_JERA AS JERARQUIA1,
'' AS COL_27,
'' AS COL_28,
'' AS COL_29,
'' AS COL_30,
'' AS COL_31,

'' AS COL_32,
'' AS COL_33,
'' AS COL_34,
'' AS COL_35,
'' AS COL_36,

'' AS COL_37,
'' AS COL_38,
'' AS COL_39,
'' AS COL_40,
'' AS COL_41,

'' AS COL_42,
'' AS COL_43,
'' AS COL_44,
'' AS COL_45,
'' AS COL_46,

'' AS COL_47,
'' AS COL_470,

'10' AS SECTOR,

'' AS COL_48,
'' AS COL_49,
'' AS COL_50,
'' AS COL_51,
'' AS COL_52,
'' AS COL_53,

COD_JERA AS JERARQUIA2,

'' AS COL_54,
'' AS COL_55,

'1' AS GR_ESTADITICA,
'1' AS CLASIFICACION,

'' AS COL_56,

'VMS0' AS GRUPO1,
'VMS0' AS GRUPO2,

'' AS COL_57,

'52' AS MATERIAL_ESTADISTICA_PRUEBA,

'0001' AS GRUPO3,
'0001' AS GRUPO4,

'KP' AS VERIFICACION_DISPO,

COD_MARCA AS MARCA,

'' AS COL_58,
'' AS COL_59,
'' AS COL_60,
'' AS COL_61,
'' AS COL_62,

'' AS COL_63,
'' AS COL_64,
'' AS COL_65,
'' AS COL_66,
'' AS COL_67,

'' AS COL_68,
'' AS COL_69,
'' AS COL_70,
'' AS COL_71,
'' AS COL_72,
'' AS COL_73,

COD_CEBE AS CENTRO_BENEFICIO, 

'' AS COL_74,
'' AS COL_75,
'' AS COL_76,

'T03'AS COMPRA,
'X' AS COL_77,

'' AS COL_78,
'' AS COL_79,

'ZMP1' AS PERFIL_PIEZA, 
COD_FABRICANTE AS FABRICANTE,
NPF AS NPF, 

'' AS COL_80,

'UN' AS CONDICION_ALMACENAJE, 

'' AS COL_81,
'X' AS COL_82,
'' AS COL_83,
'' AS COL_84,
'X' AS COL_85,
'' AS COL_86,
'V' AS COL_87,
'' as col_1002,

DESC_FABRICANTE AS CATEGORIA_VALORACION_PRUEBA,

'' AS COL_88,
'' AS COL_89,

'1' AS PRECIO, 

'' AS COL_90,
'' AS COL_91,

'ND' AS COL_92,

'' AS COL_93,
'' AS COL_94,
'' AS COL_95,
'' AS COL_96,
'' AS COL_97,

'' AS COL_98,
'' AS COL_99,
'' AS COL_100,
'' AS COL_101,
'' AS COL_102,

'' AS COL_103,
'' AS COL_104,
'' AS COL_105,
'' AS COL_106,
'' AS COL_107,

'' AS COL_108,
'' AS COL_109,

'0' AS COL_110

	FROM [dbo].[SABANA_PLANILLA_AMPLIADO_TMM]
		WHERE DESC_FILIAL = 'Tattersall Maquinarias'
GO


